const ProductData = [
  {
    product_id: "P001",
    product_title: "Apple iPhone 15 Pro Max",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "iPhone",
    price: 1299,
    description:
      "Experience the ultimate smartphone with the iPhone 15 Pro Max.",
    specification: [
      "6.7-inch Super Retina XDR display" ,
      "A17 Bionic chip",
      "Triple-camera system (48MP Main, 12MP Telephoto, 12MP Ultrawide)",
      "LiDAR Scanner",
      "Up to 2TB storage",
    ],
    availability: true,
    rating: 4.8,
  },
  {
    product_id: "P002",
    product_title: "Samsung Galaxy S23 Ultra",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Phones",
    price: 1199,
    description: "Samsung's most powerful Galaxy smartphone.",
    specification: [
      "6.8-inch Dynamic AMOLED 2X display",
      "Snapdragon 8 Gen 2",
      "Quad-camera system (200MP Main, 10MP Telephoto, 12MP Ultrawide, 10MP Periscope)",
      "5,000mAh battery",
      "Up to 1TB storage",
    ],
    availability: true,
    rating: 4.7,
  },
  {
    product_id: "P003",
    product_title: "Google Pixel 7 Pro",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Phones",
    price: 899,
    description: "The best of Google, all in the Pixel 7 Pro.",
    specification: [
      "6.7-inch OLED display",
      "Google Tensor G2",
      "Triple-camera system (50MP Main, 12MP Ultrawide, 48MP Telephoto)",
      "5G capable",
      "128GB to 512GB storage",
    ],
    availability: false,
    rating: 4.5,
  },
  {
    product_id: "P004",
    product_title: "Apple MacBook Pro 14",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Laptops",
    price: 1999,
    description: "Powerful performance with M2 Pro chip in a compact design.",
    specification: [
      "14.2-inch Liquid Retina XDR display",
      "M2 Pro chip",
      "Up to 32GB RAM",
      "Up to 2TB SSD",
      "Battery life up to 17 hours",
    ],
    availability: true,
    rating: 4.9,
  },
  {
    product_id: "P005",
    product_title: "Dell XPS 13",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Laptops",
    price: 1199,
    description: "A premium compact laptop with stunning visuals.",
    specification: [
      "13.4-inch FHD+ InfinityEdge display",
      "12th Gen Intel Core i7",
      "16GB RAM",
      "512GB SSD",
      "Battery life up to 12 hours",
    ],
    availability: true,
    rating: 4.6,
  },
  {
    product_id: "P006",
    product_title: "Apple Watch Series 8",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Smart Watches",
    price: 399,
    description: "Advanced health features in the latest Apple Watch.",
    specification: [
      "Always-on Retina display",
      "ECG and Blood Oxygen monitoring",
      "Fall detection",
      "Up to 18 hours of battery life",
      "Water resistant",
    ],
    availability: true,
    rating: 4.7,
  },
  {
    product_id: "P007",
    product_title: "Samsung Galaxy Watch 5 Pro",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Smart Watches",
    price: 449,
    description: "A smartwatch built for the outdoors.",
    specification: [
      "Super AMOLED display",
      "GPS and heart rate monitoring",
      "Body composition measurement",
      "Up to 80 hours of battery life",
      "Water resistant",
    ],
    availability: false,
    rating: 4.6,
  },
  {
    product_id: "P008",
    product_title: "Anker PowerCore 10000",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Accessories",
    price: 25,
    description: "Compact portable charger with high-speed charging.",
    specification: [
      "10,000mAh capacity",
      "High-speed charging",
      "Compact design",
      "Compatible with USB devices",
      "Overcharge protection",
    ],
    availability: true,
    rating: 4.5,
  },
  {
    product_id: "P009",
    product_title: "Sony WH-1000XM5",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Accessories",
    price: 349,
    description: "Industry-leading noise-canceling headphones.",
    specification: [
      "Advanced noise-canceling",
      "30 hours of battery life",
      "Touch controls",
      "Wireless Bluetooth connectivity",
      "Quick attention mode",
    ],
    availability: true,
    rating: 4.8,
  },
  {
    product_id: "P010",
    product_title: "Apple MacBook Air M2",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "MacBook",
    price: 1199,
    description: "Lightweight and powerful with the M2 chip.",
    specification: [
      "13.6-inch Liquid Retina display",
      "M2 chip",
      "Up to 24GB RAM",
      "Up to 2TB SSD",
      "Battery life up to 18 hours",
    ],
    availability: true,
    rating: 4.7,
  },
  {
    product_id: "P011",
    product_title: "Apple iPhone 14",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "iPhone",
    price: 799,
    description: "Apple's latest iPhone with advanced features.",
    specification: [
      "6.1-inch Super Retina XDR display",
      "A15 Bionic chip",
      "Dual-camera system (12MP Main, 12MP Ultrawide)",
      "5G capable",
      "Up to 512GB storage",
    ],
    availability: true,
    rating: 4.6,
  },
  {
    product_id: "P012",
    product_title: "Apple Watch Ultra",
    product_image: "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/A8%2Fmaxresdefault.jpg?alt=media&token=8b0f1808-b729-40eb-912b-0584168bcdc8",
    category: "Smart Watches",
    price: 799,
    description: "The most durable and capable Apple Watch ever.",
    specification: [
      "49mm Titanium case",
      "Up to 36 hours battery life",
      "Dual-frequency GPS",
      "Water resistant to 100m",
      "Depth gauge and water temperature sensor",
    ],
    availability: true,
    rating: 4.9,
  },
];

export default ProductData;
